packages:
  - .

allowBuilds:
  esbuild: set this to true or false
  sharp: true
  unrs-resolver: true
  workerd: set this to true or false

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

updateConfig:
  ignoreDependencies:
    - lucide-react
